version: '3.3'

services:

  encoder:
    image: massento
    hostname: massento_encoder
    deploy:
      resources:
        limits:
          cpus: '1'       
        reservations:
          cpus: '1'
    volumes:
      - /Users/u547059/data/noTimeMachine/shared/YT/orig/:/input
      - /Users/u547059/data/noTimeMachine/shared/YT/encoded/:/output
    environment:
      - MASSENTO_DELAY=5
      - MASSENTO_CODECS=phone_x265_norm
      - MASSENTO_DELETE_SOURCE=True
